engine:
  cycle_interval: 260  
  fetch_timeout: 220    
  auto_open: true

data:
  raw:
    skinport_items: "data/skinport/items"
    lis_skins: "data/lis-skins/items"
  aggregated:
    skinport: "data/aggregated/skinport"
    lis_skins: "data/aggregated/lis-skins"
  historical:
    skinport: "data/historical/sp_items"
    lis_skins: "data/historical/ls_items"
  reports: "data/reports"
  combined: "data/combined_markets"

skinport:
  commission_rate: 0.12

strategy:
  min_profit_pct: 20
  min_quantity: 20
  max_profit_pct: 400

risk:
  max_investment_per_item: 50
  max_total_investment: 510
  max_items_per_day: 200

html_reports:
  path: "data/html_report"