skinport:
  client_id: "dc907317e57e4481958fbd1f0c40031a"
  client_secret: "fPzfzlb3IQiB4URM0qnNHbBtuvkO7/ttNR0cyfb+AJNNVbK2fq/TjHxtdvP9PTi/qlfEg3TFyKS3B6ru9UvzUg=="

trading:
  max_spend_per_trade: 10.0  # €
  profit_margin_min: 0.12    # 12%
  cooldown_between_trades: 3600  # in seconds
  platforms_priority: ["skinport", "lisskins"]

scheduler:
  scan_interval_minutes: 30
  price_history_days: 90
